version: '3'

services:
  emexmicroservices:
    image: emexmicroservices
    build:
      context: ./EmexMicroservices
      dockerfile: Dockerfile

  webapi:
    image: webapi
    build:
      context: ./WebApi
      dockerfile: Dockerfile

  webapp:
    image: webapp
    build:
      context: ./WebApp
      dockerfile: Dockerfile
